#!/bin/sh

FILES=`cat ./files`

for file in ${FILES}
do
    DEST=./home/${file}
    SRC=${HOME}/${file}
    DIR=`dirname ${DEST}`
    if [ -e ${DEST} ];
    then
        rm -rf ${DEST}
    fi
    if [ ! -d ${DIR} ];
    then
        mkdir -p ${DIR}
    fi
    echo "Gathering : ${SRC} --> ${DEST}"
    cp -rf ${SRC} ${DEST}
done
