#!/bin/sh

FILES=`cat ./files`

for file in ${FILES}
do
    DEST=./home/${file}
    DIR=`dirname ${DEST}`
    if [ ! -d ${DIR} ];
    then
        mkdir -p ${DIR}
    fi
    cp -rf ./home/${file} ${HOME}/${file}
done
