#!/bin/sh

FILES=`cat ./files`

for file in ${FILES}
do
    DST=${HOME}/${file}
    SRC=./home/${file}
    DIR=`dirname ${DST}`
    if [ ! -d ${DIR} ];
    then
        mkdir -p ${DIR}
    fi
    echo "${SRC} --> ${DST}"
    cp -rf ${SRC} ${DST}
done
